deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: built
  on:
    branch: master

language: node_js
node_js:
  - "node"

script:
  - npm ci
  - node metalsmith.js
